GistCache = {

  init: function() {
    GridGame.gist_cache = {
      "808c86eb544d9efaf94a30efc91bdfaf": "if ((api.turn() % 2) == 0) {\n  api.towardsY();\n} else {\n  api.towardsX();\n}",
      "6634a7f381bb679ee7c2d90d93588d66": "if (typeof this.n === 'undefined') { \n  this.n = 0;\n} else {\n  this.n = (this.n + 1) % 4\n}\nif((api.turn() % 3) == 0) {\n  directions = ['towardsY', 'towardsX', 'awayY', 'awayX'];\n  api[directions[this.n]]();\n}",
      "b16df33acb0f0c7830d2ca2d656f80be": "directions = ['towardsY', 'towardsX', 'awayY', 'awayX'];\ndir = Math.floor(Math.random() * 4);\napi[directions[dir]]();\n",
      "496367ff51c27dc62ebdc473cd14f333": "const turn = api.turn();\nif (turn === 0) {\n\tthis.generator = (function* () {\n\t\tyield* [[0, 30], [1, 30]];\n\n\t\tfor (let i = 0; i < 10; ++i) {\n\t\t\tyield* [[2], [0, 2]];\n\t\t}\n\n\t\tfor (let i = 0; i < 4; ++i) {\n\t\t\tyield* [[3], [1, 2]];\n\t\t}\n\n\t\tyield* [[3], [2, 4], [1, 4]];\n\n\t\twhile (true) {\n\t\t\tfor (let i = 0; i < 30; ++i) {\n\t\t\t\tyield* [[3], [2, 2]];\n\t\t\t}\n\n\t\t\tfor (let i = 0; i < 3; ++i) {\n\t\t\t\tyield [1, 42];\n\t\t\t\tyield [0, 51];\n\t\t\t}\n\t\t}\n\t})();\n\n\tthis.nextCall = 0;\n}\nif (turn === this.nextCall) {\n\tconst [dir, delay = 1] = this.generator.next().value;\n\t[api.awayX, api.awayY, api.towardsX, api.towardsY][dir].bind(api)();\n\tthis.nextCall += delay;\n}",
      "3f69bdf2be37886ff396d0c485007e80": "//Sweeping Endgame v2\nthis.t = api.turn();\n\n//initial city setup\nif (this.t < 29) {\n   api.awayY();\n} else if (this.t < 59) {\n   api.awayX();\n\n//mid-game loop, now attempts to put cities in the two off-corners\n} else if (this.t < 400) {\n  if (this.t % 200 < 14) {\n     api.towardsY();\n  } else if (this.t % 200 > 13 && this.t % 200 < 17) {\n     api.awayX();\n  } else if (this.t % 200 > 100 && this.t % 200 < 122) {\n     api.towardsX();\n  } else if (this.t % 200 > 121 && this.t % 200 < 126) {\n     api.awayY();\n  } else if ((this.t % 8) % 3 == 1) {\n     api.towardsY();\n  } else {\n     api.towardsX(); \n  }\n\n//endgame, now sequential, not random\n} else {\n   if (this.t % 200 < 40) {\n      api.awayY()\n   } else if (this.t % 200 < 50) {\n      if (this.t % 2 == 0) {\n        api.towardsY();\n      } else {\n        api.awayX();\n      }\n   } else if (this.t % 200 < 90) {\n     api.towardsX()\n   } else if (this.t % 200 < 100) {\n      if (this.t % 2 == 0) {\n        api.awayY();\n      } else {\n        api.awayX();\n      }\n   } else if (this.t % 200 < 140) {\n     api.towardsY()\n   } else if (this.t % 200 < 150) {\n      if (this.t % 2 == 0) {\n        api.awayY();\n      } else {\n        api.towardsX();\n      }\n   } else if (this.t % 200 < 190) {\n     api.awayX()\n   } else {\n      if (this.t % 2 == 0) {\n        api.towardsY();\n      } else {\n        api.towardsX();\n      }\n   }\n}\n",
      "a0a4a9f3c8b8863392f109fdfd52af00": "if (api.turn() < 29) {\n   api.awayY();\n} else if (api.turn() < 59) {\n   api.awayX();\n} else if (api.turn() % 3 == 1) {\n   api.towardsY();\n} else {\n   api.towardsX();\n}",
      "b9a0fe99060d9be1fc617bb7262f57be": "if((api.turn() % 10) == 0) {\n  directions = ['towardsY', 'towardsX', 'awayY', 'awayX'];\n  dir = Math.floor(Math.random() * 4);\n  api[directions[dir]]();\n}",
      "7d0a88c1533fc89b2ee26484bbcafc59": "if (api.turn() < 29) {\n   api.awayY();\n} else if (api.turn() % 3 == 2) {\n   api.towardsY();\n} else {\n   api.towardsX();\n}"
    }
  }

};
