test:
  players:
    - a
    - b
    - c
dev:
  players:
    - red
    - green
match:
  players:
    - red
    - green
match_four:
  players:
    - red
    - green
    - blue
    - yellow
righttwix:
  players:
    - red
    - green
left-twix:
  players:
    - red
    - green
right-twix:
  players:
    - red
    - green
    - blue
    - yellow
